FROM amazoncorretto:21 as builder

WORKDIR /app/dictionary-api

COPY /dictionary-api .

RUN ./gradlew build --info

## Deploy
FROM amazoncorretto:21 

WORKDIR /opt

COPY --from=builder ./app/dictionary-api/build/libs/dictionary-api-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]