version: '3.8'

services:
  java-api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "8080:8080"

  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"

