# Use the official PostgreSQL image as the base image
FROM postgres:16.1

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=dictionary
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=dictionaryDB

# Expose the default PostgreSQL port
EXPOSE 5432
