server:
  port: 11001
  servlet:
    context-path: /library/api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      hbm2ddl:
        auto: create-drop
        create_namespaces: true
      format-sql: true
    show-sql: true
    database: H2