server:
  port: 8080
  servlet:
    context-path: /dev/dictionary-api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dictionaryDB}
    username: ${SPRING_DATASOURCE_USERNAME:dictionary}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: secret
    issuer: juansebohu
    expiration:
      access-token: 86400000 # 1 day

  security:
    ignored: /swagger-ui/**, /v3/api-docs/**