server:
  port: 11001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionaryDB
    username: dictionary
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


app:
  jwt:
    secret: secret
    issuer: juansebohu
    expiration:
      access-token: 86400000 # 1 day

  security:
    ignored: /swagger-resources/**, /swagger-ui.html, /v2/api-docs


# For debugging purposes - Logging

#logging:
  #level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework: DEBUG
    #org.hibernate: DEBUG