name: PR flows
run-name: Push Checks - ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Merge a develop when a PR is closed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: ./gradlew test
        working-directory: dictionary-api
      
      - name: Merge to develop if tests pass
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout develop
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin develop